### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-dew-cfrg-signature-key-blinding#16]
Since we're targeting more than EdDSA, we should update the repo name and README.

**Comment by jedisct1** [comment]
Shall we just go for "Signature key blinding"?

**Comment by chris-wood** [comment]
Yeah, that sounds reasonable to me. It captures what we're doing here. @tedeaton what do you think?

**Comment by tedeaton** [comment]
Sounds like a good name to me as well

**Comment by chris-wood** [comment]
Fixed directly on `main`.
